### ISSUE TITLE
tests fail with RuntimeError: implement_array_function method already has a docstring

### ISSUE THREAD

**Issue by TheChymera** [enthought/traits#458] opened 2019-03-18 20:00 UTC
Hello, I am getting the following test failure with `=traits-4.6.0`: 
[build.log](https://github.com/enthought/traits/files/2980029/build.log)

**Comment by mdickinson** [comment] 2019-03-19 07:50
Thanks for the report. I think this should have been fixed in #443, which is included in the Traits 5.0.0 release. For the record, it's harmless: it's a problem with the test itself, rather than the test failure indicating an issue in the core library.

Closing as a duplicate of #441.

**Comment by TheChymera** [comment] 2019-03-21 02:20
@mdickinson sadly this persists with version 5.0.0, any thoughts?
[build.log](https://github.com/enthought/traits/files/2990678/build.log)

**Comment by mdickinson** [comment] 2019-03-21 08:26
Ah, sorry; you're right. The fix wasn't made until _after_  the 5.0.0 release. (#443 was merged on Feb 15th; the 5.0.0 release was made at the end of January.) So this should be fixed on Traits master, but the fix isn't yet in any release.

I'm planning a 5.0.1 release within the next few weeks, if that helps.

**Comment by mdickinson** [comment] 2019-04-15 15:24
Traits 5.1.0 was released, and contains the fix from #443. Closing again.

**Closed by mdickinson** 2019-04-15 15:24 UTC
Labels: duplicate
