### ISSUE TITLE
clone_traits fails even with copy='deep'

### ISSUE THREAD

**Issue by jwiggins** [enthought/traits#983] opened 2020-04-06 11:33 UTC
For this minimal example:
```python
class TraitDesc(HasStrictTraits):
    name = Unicode()
    trait_type = Unicode()
    args = List()
    kwargs = Dict()

class ClassDesc(HasStrictTraits):
    name = Unicode()
    traits = List(Instance(TraitDesc))

inner_desc = ClassDesc(
    name='inner',
    traits=[
        TraitDesc(
            name='a',
            trait_type='Int',
            args=[42],
            kwargs={},
        ),
    ],
)
desc = TraitDesc(
    name='a',
    trait_type='Trait',
    args=['None', {'None': None, 'Inner': inner_desc}],
    kwargs={'stuff': 'things'},
)

desc.print_traits()
copy = desc.clone_traits(copy='deep')
print()
copy.print_traits()
```
I get the following output:
```
args:       ['None', {'None': None, 'Inner':...assDesc object at 0x105aaed00>}]
kwargs:     {'stuff': 'things'}
name:       'a'
trait_type: 'Trait'

args:       []
kwargs:     {'stuff': 'things'}
name:       'a'
trait_type: 'Trait'
```
I expect `args` to not be empty in the second `print_traits` output.

**Comment by jwiggins** [comment] 2020-04-06 11:36
Note: I do get the correct behavior with I call `clone_traits` with `traits='all'`, but I don't understand why.

**Comment by mdickinson** [comment] 2020-04-07 14:47
Assigning to the 6.1.0 milestone; we should at least investigate before the upcoming release. (Whether we can fix for the release depends on how hard or invasive the fix is.)

**Comment by midhun-pm** [comment] 2020-04-13 20:52
It's caused by a name collision with the method `traits.has_traits.HasTraits.traits`.

The method `traits.has_traits.HasTraits.trait_names` tries to call the above method, at which point, due to the name collision, we are trying to call a a list object `TraitListObject` and not a callable, throwing an exception.

 The exception is swallowed by the generic exception handler inside the method: `traits.has_traits.HasTraits.copy_traits`

Changing the name of the attribute `traits` for the class `ClassDesc` in this example to anything else will not cause this bug.

**Comment by midhun-pm** [comment] 2020-04-13 20:57
Maybe we should be having some notion of reserved keywords in `traits`.

**Comment by mdickinson** [comment] 2020-04-14 07:38
> Maybe we should be having some notion of reserved keywords in `traits`.

Somewhat related: #705, which is a documentation issue.

For this issue, perhaps we could issue a warning if a user-defined trait name conflicts with an existing method.

**Comment by jwiggins** [comment] 2020-04-14 08:15
Doh! 🤦
Thanks for pointing this out @midhun-pm

**Comment by jwiggins** [comment] 2020-04-14 13:42
Should this be closed as a PEBKAC since any problem that might be tracked here is covered by other bugs already?

**Comment by mdickinson** [comment] 2020-04-14 13:51
I'm okay with folding this into #705, but I think there is an issue here (even if it's only a documentation issue). It's not a priori obvious that there are some names that can't / shouldn't be used as trait names.

**Closed** 2020-04-14 13:52 UTC
Labels: type: bug
