### ISSUE TITLE
Date, Datetime and Time aren't documented

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1638] opened 2022-05-09 11:19 UTC
I was expecting to see the trait types `Date`, `Datetime` and `Time` in the ["Predefined Traits"](https://docs.enthought.com/traits/traits_user_manual/defining.html#predefined-traits-for-simple-types) section of the documentation.

**Comment by mdickinson** [comment] 2022-05-09 11:54
Duplicate of #1445

**Closed by mdickinson** 2022-05-09 11:54 UTC
Labels: component: documentation, resolution: duplicate
