### ISSUE TITLE
Segfault when a default method for a Str returns None

### ISSUE THREAD

**Issue by WarrenWeckesser** [enthought/traits#20] opened 2012-06-01 19:32 UTC
The following code causes a segfault after raising the expected TraitError exception (Traits 4.2.0 (from EPD 7.3) in Ubuntu 64 bit):

``` python
from traits.api import HasTraits, Str, List
from traitsui.api import View, Item, VGroup, EnumEditor


class Foo(HasTraits):

    value = Str
    choices = List(Str)

    # If the following is uncommented, the code raises the TraitError
    # exception (as it should) and does not segfault.
    #traits_view = View(Item('value', editor=EnumEditor(name='choices')))

    def _value_default(self):
        if len(self.choices) == 0:
            result = ''
        else:
            result = self.choices[0]
        # Intentional bug: missing return value, so None is returned.
        #return result

    def _choices_default(self):
        return []

if __name__ == "__main__":
    f = Foo()
    f.configure_traits()
```

**Comment by mdickinson** [comment] 2020-01-09 14:53
Closing here. This doesn't seem to be related to Traits itself, and it seems to be impossible to reproduce with current versions of ETS packages (but that's partly because wx isn't supported at the moment on Python 3).

**Closed by mdickinson** 2020-01-09 14:53 UTC
