### ISSUE TITLE
add_trait doesn't make traits "immediately available"

### ISSUE THREAD

**Issue by pierre-haessig** [enthought/traits#84] opened 2013-10-07 16:14 UTC
Starting using the `add_trait` method, I noticed a strange behavior. (using traits 4.3.0)

When adding a new trait with `add_trait`, it is not accessible before "visiting it"

``` python
class A(HasTraits):
param1 = Float(1)

a = A()
print(a.get())
# -> {'param1': 1}

# Add a trait
a.add_trait('param2', Float(2))
print(a.get())
# -> {'param1': 1}
# -> 'param2' is missing !

# Visit the trait:
a.param2
# Now param2 is visible
print(a.get())
# -> {'param2': 2, 'param1': 1}
```

(see https://gist.github.com/pierre-haessig/6870346 for complete script)

Is this an expected behavior or a bug ? Should I call some kind of _"do register my trait"_ method ?

best,
Pierre

**Comment by stefanoborini** [comment] 2017-05-26 11:28
Seems to be by design. Closing

**Closed by stefanoborini** 2017-05-26 11:28 UTC

**Comment by pierre-haessig** [comment] 2017-06-01 06:41
@stefanoborini: is there some design document that explains it?

Now of course it's pretty old and maybe it's not worth fixing it. Also, I've not used traits recently. But still, reading over this thread, it seems to be a design bug...
