### ISSUE TITLE
add_class_trait() fails on List when class has subclasses

### ISSUE THREAD

**Issue by YannGoudard** [enthought/traits#1460] opened 2021-05-12 14:21 UTC
Hi,
I have found what seems an error to me in HasTraits.add_class_trait() method (traits/has_traits.py, line 1113 in master). I use this method to add a List when I need it. It happens I use it on a class which is subclassed and it throws me "traits.trait_errors.TraitError: The 'bar_list_items' trait is already defined.".
It appears that each subclass tries to add "bar_list_items". It can be easily fixed by replacing recursive calls to add_class_trait by calls to _add_class_trait and passing it "is_subclass", like this:

```
1175        # Check to see if the trait has additional sub-traits that need to be
1176        # defined also:
1177        handler = trait.handler
1178        if handler is not None:
1179            if handler.has_items:
1180                cls._add_class_trait(name + "_items", handler.items_event(), is_subclass)
1181            if handler.is_mapped:
1182                cls._add_class_trait(name + "_", mapped_trait_for(trait, name), is_subclass)
```
I attach an example to reproduce the error.

[add_class_trait_error.txt](https://github.com/enthought/traits/files/6466722/add_class_trait_error.txt)

**Comment by mdickinson** [comment] 2021-05-12 14:56
Thanks for the report. Behaviour confirmed on Traits master / Python 3.9:
```
(traits) mdickinson@mirzakhani traits % python ~/Desktop/add_class_trait_error.py 
Traceback (most recent call last):
  File "/Users/mdickinson/Desktop/add_class_trait_error.py", line 15, in <module>
    A.add_class_trait("bar_list", tapi.List)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/has_traits.py", line 1142, in add_class_trait
    subclass._add_class_trait(name, trait, True)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/has_traits.py", line 1180, in _add_class_trait
    cls.add_class_trait(name + "_items", handler.items_event())
  File "/Users/mdickinson/Enthought/ETS/traits/traits/has_traits.py", line 1138, in add_class_trait
    cls._add_class_trait(name, trait, False)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/has_traits.py", line 1173, in _add_class_trait
    raise TraitError("The '%s' trait is already defined." % name)
traits.trait_errors.TraitError: The 'bar_list_items' trait is already defined.
```

Here's the script, for reference:
```python
import traits.api as tapi


class A(tapi.HasTraits):
    foo = tapi.Int


class AB(A):
    pass


A.add_class_trait("bar_float", tapi.Float)
# OK

A.add_class_trait("bar_list", tapi.List)
# traits.trait_errors.TraitError: The 'bar_list_items' trait is already defined.

A.add_class_trait("bar_dict", tapi.Dict)
# traits.trait_errors.TraitError: The 'bar_dict_items' trait is already defined.
```

**Comment by mdickinson** [comment] 2021-05-12 16:42
> It can be easily fixed by replacing recursive calls to add_class_trait by calls to _add_class_trait and passing it "is_subclass", like this

Thanks for this; agreed that as well as being an easy fix, it looks like the "right" fix. #1461 implements this fix, and adds tests.

**Comment by mdickinson** [comment] 2021-05-13 07:53
Okay, the fix in #1461 is now actually working. @YannGoudard If you have the opportunity to confirm that #1461 solves your issue, please let us know. (If not, that's fine.)

**Comment by YannGoudard** [comment] 2021-05-17 08:00
Thanks @mdickinson , this fix solves my issue. 
For information, I still work with a Python 2.7 environment and traits 4.5.0. I have fixed the same lines and it works too.

**Comment by mdickinson** [comment] 2021-05-17 08:06
@YannGoudard Thanks for the confirmation! I'm going to keep this issue open until the fix is merged into master.

**Comment by mdickinson** [comment] 2021-05-17 09:28
Fix now merged. Closing.

**Closed by mdickinson** 2021-05-17 09:28 UTC
Labels: type: bug
