### ISSUE TITLE
Listener expression 'some_dict.items' not working for cached_property

### ISSUE THREAD

**Issue by bebaek** [enthought/traits#1264] opened 2020-07-31 20:42 UTC
Certain part of our project code that uses `cached_property` used to work fine until recently. I suspect the upgrade from traits 5.2 to 6.1.0 broke this. I saw a similar error from `@on_trait_change` too, which could be trivially resolved by `@observe`. Here's a comparable example:
```python
import uuid
from traits.api import *


# This doesn't work
class Foo(HasTraits):
    bar = Dict(key_trait=Int, value_trait=Instance(uuid.UUID))

    # This doesn't help
    # bar = Dict(key_trait=Int, value_trait=Instance(uuid.UUID),
    #            comparison_mode=ComparisonMode.identity)

    baz = Property(depends_on='bar.items')

    @cached_property
    def _get_baz(self):
        print('getter called')
        return 1


foo = Foo()
foo.bar[1] = uuid.uuid4()
foo.bar[1] = uuid.uuid4()
```
This is the error message:
```
Exception occurred in traits notification handler for object: <__main__.Foo object at 0x7f12aa49ce08>, trait: bar_items, old value: <undefined>, new value: TraitDictEvent(removed={}, added={1: UUID('d251feb5-4696-408f-8c4e-1d78eeab5f97')}, changed={})
Traceback (most recent call last):
  File "/home/bbaek/.edm/envs/apc-petro/lib/python3.6/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/bbaek/.edm/envs/apc-petro/lib/python3.6/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/home/bbaek/.edm/envs/apc-petro/lib/python3.6/site-packages/traits/traits_listener.py", line 471, in handle_dict_items
    self.handle_dict(object, name, new.removed, new.added)
  File "/home/bbaek/.edm/envs/apc-petro/lib/python3.6/site-packages/traits/traits_listener.py", line 466, in handle_dict
    register(obj)
  File "/home/bbaek/.edm/envs/apc-petro/lib/python3.6/site-packages/traits/traits_listener.py", line 347, in register
    trait = new.base_trait(name)
AttributeError: 'UUID' object has no attribute 'base_trait'
... 3 more of this exception ...
```

**Comment by mdickinson** [comment] 2020-08-03 06:48
@bebaek Thanks for the report!

Confirmed the bug, but I'm not seeing a regression here: I see the same behaviour with Traits 5.1 as on Traits master. Is it possible that the breakage was caused by some other change?

**Comment by mdickinson** [comment] 2020-08-03 07:20
Actually, I think this is a bug in the example you posted: if you're using the old `on_trait_change` mechanism rather than the new `observe`, you want to listen to `bar_items`, not `bar.items`. Otherwise it'll expect the value type to be a `HasTraits` instance with an `items` trait on it.

Admittedly the error message could be better, but this isn't looking like a bug in traits.

**Comment by mdickinson** [comment] 2020-08-03 07:27
Closing here; I'll follow up on the project issue as necessary.

**Closed by mdickinson** 2020-08-03 07:27 UTC
Labels: type: bug
