### ISSUE TITLE
Consider reverting getting default from a collection in Enum

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#812] opened 2020-01-24 14:33 UTC
This issue is for considering changing this line in `BaseEnum._get`:

https://github.com/enthought/traits/blob/27210f5fe74c1a5a074b23dd36c931a2b4cb5d3b/traits/trait_types.py#L2061

Back to 
```
value = values[0]
```

So we maintain the existing support for getting the first item as the default value in `traits <= 5.2.0`. This means users using `enum.Enum` with `traits.Enum` will need to provide a way to get a default value explicitly. Note that support for `enum.Enum` in `traits.Enum` is a new feature for 6.0.0.

Related to #389 and #685

**Comment by corranwebster** [comment] 2020-01-27 09:44
If I understand correctly, the issue is that if a dictionary is used for the `values` trait that this will start working, but we don't want people to start relying on that?

Unfortunately in dynamic cases we would probably need to have some way of specifying a dynamic default to go along with the dynamic set of valid values, which seems complex.  Options look like:

- revert support for `enum.Enums`; but this wouldn't really fix the "problem" of things other than tuples and list being valid for dynamic values (things like arrays, strings, bytes, pretty much anything which is a `Sequence` would work; strings would be particularly problematic because `in` corresponds to "substring of" not "element of")
- allow `enum.Enum`s for non-dynamic values, but prohibit for dynamic ones.
- type test to ensure that the dynamic values have to be of `EnumType` (ie. currently list, tuple or enum.Enum)
- type test, but broaden to allow any `Sequence` except strings; plus `enum.Enum` (and maybe when we drop 3.5, dictionaries as well)
- go really broad: if containment and iteration are defined, we're good; beyond that buyer beware.  I think this might roughly correspond to the `Collection` ABC (or maybe `Container` plus `Iterable`) if we want to do type checking.  If the user wants to use a `set` with a random default, fine.  We might need to special-case strings still.

**Comment by mdickinson** [comment] 2020-01-28 08:06
Closed by #828

**Closed by mdickinson** 2020-01-28 08:06 UTC
