### ISSUE TITLE
Extra comma in comma-separated traits name causes events to be triggered on other traits

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traits#418] opened 2018-12-05 20:26 UTC
A trailing comma in a set of single-string comma-separated traits causes events to trigger for all traits. Example:

```python
from traits.api import *


class Thing(HasTraits):
    one = Str('one')
    two = Str('two')
    three = Str('three')

    @on_trait_change('one,two,')
    def dosomething(self):
        print('hiya')


if __name__ == '__main__':
    t = Thing()

    t.three = 'four'
    # prints hiya

    t.fancy_new_trait = 'five'
    # prints hiya
```

I'm not sure whether this is intended behavior, but it at least wasn't expected for me since it is not analogous with list behavior where a trailing comma is ignored (i.e., `['one', 'two',]`). This lead to a hard to a identify bug elsewhere in some code.

Version info: traits 4.6, python 2.7.15

**Comment by mdickinson** [comment] 2018-12-06 08:03
Duplicate of #406?

**Comment by notmatthancock** [comment] 2018-12-06 13:55
Yes, indeed. I searched first, I swear :grinning:

**Closed** 2018-12-06 13:55 UTC
Labels: duplicate
