### ISSUE TITLE
setattr_original_value flag is ignored when setting a value through the _default method

### ISSUE THREAD

**Issue by ievacerny** [enthought/traits#1087] opened 2020-05-15 12:25 UTC
`Expression` and `AdaptsTo` traits have `setattr_original_value=True` but it is ignored when setting the default value through a `*_default` method:
``` python
def test_set_value_original(self):
    class Foo(HasTraits):
        bar = Expression()

    f = Foo()
    f.bar = "1"
    self.assertEqual(f.bar, "1") # pass

def test_default_value_original(self):
    class Foo(HasTraits):
        bar = Expression(default_value="1")

    f = Foo()
    self.assertEqual(f.bar, "1")  # pass

def test_default_method_original(self):
    class Foo(HasTraits):
        bar = Expression()

        def _bar_default(self):
            return "1"

    f = Foo()
    self.assertEqual(f.bar, "1")  # fail
```

1) The flag is used in `setattr_trait` to avoid validation (`value` is the validated one): https://github.com/enthought/traits/blob/e510c11d20e189443e18fb371ab8a70086e7546c/traits/ctraits.c#L2418-L2419

2) Validation of `default_value` set via trait definition is up to individual trait classes, so it's not a problem here.

3) However, in case of a `*_default` method, it goes through validation without checking the flag:
https://github.com/enthought/traits/blob/e510c11d20e189443e18fb371ab8a70086e7546c/traits/ctraits.c#L1810-L1821

**Comment by mdickinson** [comment] 2020-05-15 12:27
Thanks! Marking as low priority for this release: (if we can get a fix in, then great, but it looks like this is a long-standing problem rather than a recent regression, and it shouldn't block the release if the timing doesn't work out).

**Comment by ievacerny** [comment] 2020-05-15 12:29
This is blocking https://github.com/enthought/traits/issues/1081 because `Expression` then tries to map a value that has already been mapped. The fix shouldn't take long

**Comment by mdickinson** [comment] 2020-05-15 12:30
> This is blocking #1081

Ah, okay. Sorry. I'll remove the priority label.

**Closed** 2020-05-15 17:37 UTC
Labels: type: bug
