### ISSUE TITLE
Awkward behavior when instantiating cTrait

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#671] opened 2019-12-17 13:10 UTC
```
>>> from traits.ctraits import cTrait
>>> cTrait(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'traits.ctraits.cTrait'> returned NULL without setting an error
>>> cTrait(11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'traits.ctraits.cTrait'> returned NULL without setting an error
>>> cTrait(1)
<traits.ctraits.cTrait object at 0x102615f48>
```

Note that adding a `import traits.traits` forces the expected behavior - 

```
>>> import traits.traits
>>> cTrait(11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
traits.trait_errors.TraitError: Invalid argument to trait constructor.
```

**Comment by mdickinson** [comment] 2019-12-17 13:32
This is a bug, pure and simple: somewhere in `ctraits.c`, we're violating the invariant that a `PyObject *`-returning C function should always set an exception when returning `NULL`. Should be an easy fix for someone prepared to dive into the Python C-API.

**Comment by rahulporuri** [comment] 2019-12-17 13:33
AFAIK, `cTrait` instantiation is handled by `trait_init` but i don't see anything wrong in the function/method - https://github.com/enthought/traits/blob/ba7c10fa28666219e276c7eeeac7e3e7168a45c2/traits/ctraits.c#L2572-L2587

**Comment by mdickinson** [comment] 2019-12-17 13:43
@rahulporuri I can't reproduce this on a clean build, on master:
```
>>> from traits.ctraits import cTrait
>>> cTrait(1)
<traits.ctraits.cTrait object at 0x7fe8501649a8>
>>> cTrait(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
traits.trait_errors.TraitError: Invalid argument to trait constructor.
>>> cTrait(0)
<traits.ctraits.cTrait object at 0x7fe850164f48>
>>> cTrait(9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
traits.trait_errors.TraitError: Invalid argument to trait constructor.
```

Can you double check that you have a clean build, and give more information about the system that you're seeing this on?

**Comment by mdickinson** [comment] 2019-12-17 13:44
> I can't reproduce this on a clean build, on master:

Ah, sorry; I'd done an `import traits.api` previously. Without that, I _can_ reproduce.

**Comment by rahulporuri** [comment] 2019-12-17 13:49
> somewhere in ctraits.c, we're violating the invariant that a PyObject *-returning C function should always set an exception when returning NULL.

If that were the case, shouldn't we still be seeing an issue even after we do `import traits.traitss`?

**Comment by mdickinson** [comment] 2019-12-17 13:54
Okay, so not necessarily simple to solve: the issue is that until `traits.traits` is imported, the global `TraitError` in `ctraits.c` is not defined.

**Comment by mdickinson** [comment] 2019-12-17 13:59
So I think the right solution is to have `ctraits.c` import `TraitError` directly from the `trait_errors` module (in the module initialization). Before we do that, to avoid circular imports, we may have to remove the `trait_base` import from `trait_errors`, possibly by replicating the `class_of` function.

**Comment by mdickinson** [comment] 2019-12-17 14:09
Another option is to move `TraitError` in its entirety into `ctraits.c`, but there's enough logic in it that that would be a bit messy. There may be a middle ground that makes sense: move `TraitError` into `ctraits.c`, but move some of the logic for constructing error messages outside of the`TraitError` class.

**Comment by mdickinson** [comment] 2019-12-17 14:12
(Note that whatever fix we apply for `TraitError` likely also needs to be applied for `DelegationError`, too.)

**Comment by rkern** [comment] 2019-12-17 15:46
There are a number of other things that several other pure Python modules inject into `ctraits` (`grin 'ctraits\._'`). It's written on the assumption that everyone imports `traits.api` first. This is actually a holdover from when we exposed everything in `traits/__init__.py`, which mechanically guaranteed that no matter how specific you tried to import something from `traits`, you always got the fully-initialized version.

I'm not sure how much I would fuss over the behavior when directly importing `traits.ctraits` before anything else. I'd rather make it private `traits._ctraits` to emphasize this. It's possible that these exceptions are easier to fix than the others and more serious, in which case, sure, let's fix them. But real use cases should still use `traits.api` always.

**Comment by rahulporuri** [comment] 2019-12-18 07:55
> There are a number of other things that several other pure Python modules inject into ctraits (grin 'ctraits\._').

I'm concerned that there could be similar issues if a user directly imports from a different traits submodule which doesn't implicitly inject everything needed to `traits.ctraits`.

Apart from that, i'm fine with closing this specific issue as a "won't fix" and saying that everyone should always inherit from `traits.api`.

**Comment by mdickinson** [comment] 2019-12-18 10:47
Long term, It Would Be Nice To get rid of all the circular dependencies. But that may not be sufficiently high priority to ever bubble up into the actual things-we'll-do list.

For this particular issue, yet another (fairly cheap and easy) option is to add an explicit `NULL` check so that we're not calling `PyErr_SetString` with an unexpected `NULL`. This time we got a `SystemError`, but there's no reason that `PyErr_SetString` should handle `NULL` gracefully, and the next time it could be a segfault. But as @rkern points out, this won't happen in normal use, there are many more places where this sort of thing happens, and adding these sort of `NULL` checks everywhere may be unrealistic.

On balance, I still think it's worth doing in this case.

**Comment by corranwebster** [comment] 2019-12-23 16:07
Having written a dumb fix for this, I think there is no reason that we couldn't instead use the solution where we just import from `traits.trait_errors` and get rid of the injection or `TraitError` into `ctraits.c` completely: the dependencies of `trait_errors` are `traits.trait_base`, `traits.etsconfig`, `traits.etsconfig.api`, and `traits.etsconfig.etsconfig`.

**Closed** 2020-01-03 11:10 UTC
Labels: bug
