### ISSUE TITLE
Fix/Remove download URL

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/traits#107] opened 2013-12-17 18:24 UTC
The download URL specified in the setup.py file is wrong and shows up as a broken link on PyPI. 
    download_url = ('http://www.enthought.com/repo/ets/traits-%s.tar.gz' %
                    d['**version**']),

We should fix it or remove the attribute altogether since we are now uploading the tar.gz itself.

**Comment by rahulporuri** [comment] 2019-02-03 10:53
ha. apparently i fixed this issue in #290 but the issue is still open. closing.

**Closed by rahulporuri** 2019-02-03 10:53 UTC
Labels: bug
